- hosts: ansible1
  gather_facts: no
  tasks:
    - name: Install Jenkins Job DSL Plugin
      jenkins_plugin:
        name: job-dsl
        state: present

    - name: Create Jenkins pipeline job
      jenkins_job:
        config: |
          pipelineJob('Your_Jenkins_Pipeline_Job_Name') {
              triggers {
                  cron('0 2 1 * *')
              }
              definition {
                  cps {
                      script('''
                          pipeline {
                              agent any
                              stages {
                                  stage('System Update') {
                                      steps {
                                          script {
                                              // Run system update based on the OS type
                                              if (isUnix()) {
                                                  sh 'apt update -y'
                                              } else {
                                                  sh 'yum update -y'
                                              }
                                          }
                                      }
                                  }
                                  stage('Execute Ansible Playbook') {
                                      steps {
                                          ansiblePlaybook(
                                              playbook: 'path/to/playbook.yml',
                                              inventory: 'path/to/inventory.yml',
                                              colorized: true,
                                              ansibleName: 'Your_Ansible_Installation_Name'
                                          )
                                      }
                                  }
                              }
                          }
                      ''')
                  }
              }
          }
        state: present
