---
- hosts: all
  ignore_errors: True
  become: True
  tasks:
    - name: Create a user
      user:
        name: alix
        comment: Alix Stearns

    - name: Create a file on the target host
      file:
        path: /tmp/ansiblefile
        state: touch

    - name: Create a directory
      file:
        path: /opt/directory_ansible
        state: directory

    - name: Install Apache
      package:
        name: "{{ 'httpd' if ansible_distribution == 'Amazon' else 'apache2' }}"
        state: present
      when: ansible_distribution == "Amazon" or ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

    - name: Start the Apache service
      service:
        name: "{{ 'httpd' if ansible_distribution == 'Amazon' else 'apache2' }}"
        state: started
      when: ansible_distribution == "Amazon" or ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

